{{ if .Values.olm }}
apiVersion: tackle.konveyor.io/v1alpha1
kind: Addon
metadata:
  name: myaddon
  namespace: konveyor-tackle
spec:
  container:
    image: quay.io/konveyor/tackle2-addon-analyzer:release-0.8
    imagePullPolicy: Always
    name: myaddon
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 512Mi
  task: mytask
{{ end }}
